services:
  werkspot.bing_ads_api_client:
    class: Werkspot\BingAdsApiBundle\Api\Client
    arguments:
      - "@werkspot.request_new_access_token"
      - "@bing.client.proxy"
      - "@bing.client.helper.zip"
      - "@bing.client.helper.csv"

  bing.client.proxy:
    class: BingAds\Proxy\ClientProxy

  bing.client.helper.zip:
    class: Werkspot\BingAdsApiBundle\Api\Helper\Zip
    arguments:
      - "@guzzle.client"

  bing.client.helper.csv:
    class: Werkspot\BingAdsApiBundle\Api\Helper\Csv

  guzzle.client:
    class: GuzzleHttp\Client

  werkspot.request_new_access_token:
    class:  Werkspot\BingAdsApiBundle\Guzzle\RequestNewAccessToken
    arguments:
      - "@guzzle.client"
