services:
  werkspot.bing_ads_api_client:
    class: Werkspot\BingAdsApiBundle\Api\Client
    arguments: ["@werkspot.request_new_access_token"]

  guzzle.client:
    class: Guzzle\Http\Client

  werkspot.request_new_access_token:
    class:  Werkspot\BingAdsApiBundle\Guzzle\RequestNewAccessToken
    arguments: ["@guzzle.client"]
